src/main/java/bsh/BlockNameSpace.java, src/main/java/bsh/Interpreter.java, src/main/java/bsh/NameSpace.java, src/main/java/bsh/Variable.java, src/test/java/bsh/Namespace_chaining.java
Resolve IllegalAccesException calling setVariable.
Basically the compiler has a problem with us creating creating new objects without the caller
having a reference. So we want to get the new variable reference back and have the variable
update itself via reference
Ambiguous constructor for NameSpace.
Casting the null references won't cut it anymore, the signature java has is  (null, String)
and there are two constructors that satisfy this. Commented one of them out as a
quick fix.
Namespace chaining test now succeeds.
=> Namespace chaining

src/test/java/bsh/classpath/BshClassPathTest.java, src/test/resources/test-scripts/array1.bsh, src/test/resources/test-scripts/strings.bsh
This patch add a test for postfix array operators.  There does not appear to be any problem, just adding to the test coverage.
=> Test for array post fix operator

src/test/java/bsh/classpath/BshClassPathTest.java, src/test/resources/test-scripts/strings.bsh
This patch fixes a couple of tests that were failing in a Window environment.  It replaces the hardcoded path and line separator characters with system properties.
=> Add system independent properties for line and path separator

src/main/java/bsh/Operators.java
Fixed https://github.com/beanshell/beanshell/issues/522
Prevent two cases of division by zero error
=> Fix issue 522 

src/main/java/bsh/classpath/ClassManagerImpl.java
This is a simple test case for performance turning.
The origin type `Vector` will use O(n) time on `removeElement`.
```java
package bsh;
import java.util.Scanner;
public class PerformanceStateTest {
public static String getName(String s) {
return s + "A";
}
public static void main(String[] args) {
final Interpreter interpreter = new Interpreter();
Runtime runtime = Runtime.getRuntime();
long usedMemoryBefore = 0;
long usedMemoryAfter = 0;
long start;
long end;
Scanner cin = new Scanner(System.in);
//		
cin.next();
try {
interpreter.eval("import bsh.PerformanceStateTest;");
interpreter.eval("a = \"1\" + \"2\";");
interpreter.eval("String getName(String s) { return \"\" + PerformanceStateTest.getName(s); }");
interpreter.eval("String getName2(String s) { if (s.charAt(0) == '1') return s + …
```
=> Performance: O(1) Listener add/delete

build.xml, engine/src/bsh/engine/BshScriptEngine.java, engine/src/bsh/engine/BshScriptEngineFactory.java, engine/src/bsh/engine/ScriptContextEngineView.java
Apply to tag 2.1.0 to fix broken build of bsh-engine.jar, bump version to 2.1.1.
=> fix broken 2.1.0 build of bsh-engine.jar

src/test/resources/test-scripts/exceptions5.bsh
Issue #395 indicated NPE on ParseException method getCurrentLineNumber().  This is fixed in the current code base but add this test anyway.
=> Add test that ParseException has currentToken filled in

src/test/resources/test-scripts/accessibility.bsh
This patch will change the accessibility test script to make sure that a test for no access to public and package protected fields and methods is allowed.  The previous test script would not perform these tests
if the haveAccessibility capability was not present, but this capability is not required for the test.
=> Make sure that private access tests are run

pom.xml, src/main/java/bsh/classpath/BshClassPath.java, src/test/java/bsh/classpath/BshClassPathTest.java
Update jacoco version to one that is compatible with Java 16
Paper over the change in exception thrown by one of the jdk classes related to jars, and adjust one of the tests to match
Fix for issue #616
=> Minor changes to allow building with JDK 16

src/main/java/bsh/BSHImportDeclaration.java, src/main/java/bsh/NameSpace.java, src/main/resources/bsh/commands/print.bsh, src/test/java/bsh/classpath/BshClassPathTest.java, src/test/resources/test-scripts/import5.bsh
Move the accessor for ambigName to after the check for superImport. If doing a superImport the ambigName access will cause an NPE, yet the ambigName is not required for this case.
=> Fix NPE when doing "import *;"

src/main/java/bsh/classpath/ClassManagerImpl.java, src/test/resources/test-scripts/classbadcase.bsh
Let the NoClassDefFoundError class loader error fall through so that BeanShell can continue with it's loading efforts.  If the class cannot be loaded than an EvalError will eventually be thrown.
I don't know if this patch is doing the right thing (there is no right answer here), but I think for Window anyway it is better than the current situation.  At least with this patch the error will get wrapped with an EvalError.
Related to #556, I think that this shows a case where there is a use for a recoverable error type.  I can see in this situation that there could be cases where is an attempt to load a class in a script.  The class is not found, and if the error could be caught then the script could go on with plan B.
=> Handle the situation of a NoClassDefFoundError during class loading.

src/main/jjtree/bsh.jjt, src/test/java/bsh/OperatorPrecedenceTest.java, src/test/resources/test-scripts/array2.bsh
Here is a fix for issue #590 as well as a more complete fix for issue #568.  Both of these were caused by the operator precedence rules bring dropped in an earlier commit.
This reverts commit 8e712bad002f33e5238dd00a0cb7c2ba2760322e.
This commit also adds a few tests that operator precedence in BeanShell behaves the same as Java
=> Revert "Grammar optimisation reducing 17 productions down to 4."

src/main/java/bsh/engine/ScriptContextEngineView.java, src/test/java/bsh/TestBshScriptEngine.java
Fix the JSR223 script engine plugin so update variables in the same scope that they are found in.  The previous version would always set variables in the ENGINE_SCOPE, thus causing global scope variables to be shadowed.
Add tests for correctness.
This PR provides a fix for issue #607.
=> Fix the JSR223 script engine

src/main/java/bsh/Invocable.java, src/test/resources/test-scripts/Data/moduleAccess.xml, src/test/resources/test-scripts/moduleAccess.bsh
Strong encapsulation in Java 16+ causes problems for MethodHandle lookups.
In case there is an AccessException when looking up a method handle this fix will continue searching up the class inheritance hierarchy to find an accessible method.
=> Fix for issue #615 

src/main/java/bsh/BshClassManager.java, src/main/java/bsh/BshMethod.java, src/main/java/bsh/ClassGenerator.java, src/main/java/bsh/ClassGeneratorUtil.java, src/main/java/bsh/DelayedEvalBshMethod.java, src/main/java/bsh/Invocable.java, src/main/java/bsh/NameSpace.java, src/main/java/bsh/Reflect.java, src/main/java/bsh/This.java, src/main/java/bsh/Types.java, src/test/java/MethodSelection.java, src/test/java/bsh/BshMethodTest.java, src/test/java/bsh/ReflectTest.java, src/test/java/bsh/TypeParametersTest.java, src/test/resources/test-scripts/methodselection.bsh, src/test/resources/test-scripts/varargs.bsh
Fix for issue #620.
Closer following of JLS 15.12.2 method resolution rules.
Propagate VarArgs flag to generated methods.
Better marshalling of arguments in varargs methods.
Update test cases.
This touched a few more files than I expected but it turned out that there were a few more loose ends.
=> Better handling of VarArgs methods and constructors.

src/main/java/bsh/BshMethod.java, src/test/resources/test-scripts/eval.bsh, src/test/resources/test-scripts/run.bsh
Fixes #508
Override namespace looses its local namespace  flag, causing duplicate blocked methods to fail on subsequent calls.
Added unit tests to prove fixes.
=> Block namespace methods fix.

src/main/java/bsh/BSHArrayDimensions.java, src/main/java/bsh/BSHPrimarySuffix.java, src/main/java/bsh/BshArray.java, src/main/java/bsh/Primitive.java, src/main/java/bsh/Reflect.java, src/main/java/bsh/Types.java, src/test/java/bsh/TypesTest.java, src/test/resources/test-scripts/TestHarness.bsh, src/test/resources/test-scripts/arraydims.bsh, src/test/resources/test-scripts/bean_properties.bsh, src/test/resources/test-scripts/expression_array.bsh, src/test/resources/test-scripts/expression_entry.bsh, src/test/resources/test-scripts/expression_map.bsh, src/test/resources/test-scripts/expression_slice.bsh, src/test/resources/test-scripts/primitives_assignment.bsh
Array dimensions accept all number types
Array indexes accept all number types
Array slices accept all number types
List dimensions accept all number types
List indexes accept all number types
List slices accept all number types
Entry array indexes accept all number types
Improve exception messages and add cause.
Improve assert for error message to include cause. Improve Primitive intValue to also cast for value. Added quick exit condition for cast to existing type. Added precision to Primitive boxType and unboxType. Optimize Types use of Primitive wrap and unwrap.
Added extensive unit tests for all number types.
Fixes #652 and #658
=> All number types for array arguments.

src/main/jjtree/bsh.jjt, src/test/java/bsh/OperatorPrecedenceTest.java, src/test/resources/test-scripts/operators.bsh
- set up productions in reverse order of precedence
- split productions that contain operators of different precedence
- join productions that have operators of similar precedence
- use tokens instead of strings
- add test case
- minor cleanup
This should fix the problem with 1+2*3=9 as noted in #590 and probably elsewhere.  Simply reverting the patch that broke operator precedence wasn't acceptable, and with no one else stepping up I went ahead and redid this.  So basically this RP is almost the same as before but fixes mod/power precedence.  I retained the reduction of productions in the unary expression and elimination of one lookahead from the cast expression.  Tokens are used instead of strings because a one point this was the strong recommendation for better performance from the …
=> Fix the problem with operator precedence (#590)

src/conf/version.properties, src/main/java/bsh/BSHAllocationExpression.java, src/main/java/bsh/BSHBlock.java, src/main/java/bsh/BSHEnhancedForStatement.java, src/main/java/bsh/BSHForStatement.java, src/main/java/bsh/BSHMethodDeclaration.java, src/main/java/bsh/BSHTryStatement.java, src/main/java/bsh/BlockNameSpace.java, src/main/java/bsh/BshMethod.java, src/main/java/bsh/Name.java, src/main/java/bsh/NameSpace.java, src/main/java/bsh/This.java, src/test/java/bsh/PreparsedScriptTest.java, src/test/resources/test-scripts/eval.bsh, src/test/resources/test-scripts/late_binding.bsh, src/test/resources/test-scripts/scripted_object.bsh
Merge of work done at #672
Fix issues with block name space cache may help #655
Fix #659 methods returning This reference
Fix #676 with additional tests
Fixes #508 again commands to exclude namespace override 
Improve for, enhanced for, while, and try-catch use of block name spaces 
Added more debug info for methods, commands and variables 
Fixed some generics for class types
Refactored this and super implementations and addressed commented concerns
=> late binding and block name space cache

src/conf/version.properties, src/main/java/bsh/BshMethod.java, src/main/java/bsh/NameSpace.java, src/main/java/bsh/This.java, src/test/resources/test-scripts/cloneable.bsh, src/test/resources/test-scripts/clonethis.bsh
Fixes #421 which originally reported the problems with cloning scripted objects. 
Had to deep copy all the contexts and most references to finally be able to produce two independent instances after a clone. Also completed the existing attempt to implement cloning, and we now return an actual instance instead of just copied This namespace.
=> Fix cloneable support.

src/conf/version.properties, src/main/java/bsh/BSHBlock.java, src/main/java/bsh/BlockNameSpace.java, src/main/java/bsh/util/ReferenceCache.java, src/test/java/bsh/ReferenceCacheTest.java, src/test/resources/test-scripts/closurescoping2.bsh
I am too tired to comprehend the why, just taking the win with a smile.
Found [the explanation](https://github.com/beanshell/beanshell/pull/672#issuecomment-1355230755) for these weird closure tests that don't seem to be testing for anything specific other than lets see how obscure we can block scope and lets throw in a couple of `x` variables for style. About how it works with the revert but not on HEAD...so I tried it on.
Was as said cannot scope x, even though it is right there.
https://github.com/beanshell/beanshell/blob/b0e6811a4358ee4505a07e86d93a9e46b1eec780/src/test/resources/test-scripts/closurescoping2.bsh#L32-L44
Something reminded me that the revert patch removed the clear namespace, since everything is going to gc anyway there is no bother. But since we are clearing the …
=> All just miraculously working

src/conf/version.properties, src/main/java/bsh/BshClassManager.java, src/main/java/bsh/Interpreter.java, src/main/java/bsh/Name.java, src/main/java/bsh/Reflect.java, src/test/java/bsh/InterpreterTest.java, src/test/java/bsh/ReferenceCacheTest.java
Interpreter allows for multiple `eval` calls and for this purpose certain state is kept. Added reset method to release additional resources and when completely done with interpreter. fixes #413
=> Add reset interpreter method

pom.xml, src/conf/version.properties, src/main/java/bsh/BSHTryStatement.java, src/test/resources/test-scripts/trycatch_ome.bsh, src/test/resources/test-scripts/tryreturn.bsh
Fixes #369 properly handle OutOfMemoryError thrown in try blocks, caught and handled to continue processing data.
=> Implement catch OutOfMemoryError.

bsh-bsf-engine/src/main/java/bsh/util/BeanShellBSFEngine.java
Beanshell emitting NPE's via the BSF integeration just throws an error reporting a "NullPointerException" in line 0.
This fix adds meta data to the NPE giving the line number and the offending line.
Fixes #572
=> NPE reporting fix

src/conf/version.properties, src/main/java/bsh/Interpreter.java, src/main/resources/bsh/commands/unset.bsh, src/test/java/bsh/InterpreterTest.java, src/test/resources/test-scripts/unsetvars.bsh
Fixes #497 allow changing prompt and prompt function
Fixes #505 unset to properly unset variables
Also fixes problem with loading .bshrc file
Fix repl resources not being closed
Fix debug output before console is set
=> Fix interpreter prompt and unset

src/conf/version.properties, src/main/java/bsh/BSHTypedVariableDeclaration.java, src/main/java/bsh/Interpreter.java, src/main/java/bsh/NameSpace.java, src/main/java/bsh/Reflect.java, src/main/java/bsh/This.java, src/main/java/bsh/Types.java, src/main/java/bsh/Variable.java, src/test/java/bsh/InterpreterTest.java, src/test/resources/test-scripts/class3.bsh, src/test/resources/test-scripts/classsuper3.bsh
Fixes #358 cast instance This for generated super type
Fixes #357 make super hidden variables ačcessible
Fixed get super namespace to include class namespace of parent classes not just scope
Cast to instance This and allow assignment to typed variable of cast type 
Instance this cast variable getClass reports the class of the instance
=> Hidden field access on super classes

src/conf/version.properties, src/main/java/bsh/BSHClassDeclaration.java, src/main/java/bsh/BSHEnhancedForStatement.java, src/main/java/bsh/BSHFormalParameters.java, src/main/java/bsh/BSHTryStatement.java, src/main/java/bsh/BshMethod.java, src/main/java/bsh/ClassGeneratorUtil.java, src/main/java/bsh/DelayedEvalBshMethod.java, src/main/java/bsh/Modifiers.java, src/main/java/bsh/ParseException.java, src/main/java/bsh/Reflect.java, src/main/java/bsh/This.java, src/test/java/bsh/ReflectTest.java, src/test/resources/test-scripts/expression_entry.bsh, src/test/resources/test-scripts/expression_map.bsh, src/test/resources/test-scripts/modifiers.bsh, src/test/resources/test-scripts/scripted_object.bsh
A drop in replacement still serves the same purpose, to capture modifier names through the parser but instead of storing the text in a collection the modifiers are translahe to their int values and stored as a distinct bit definition compatible with Modifier and ASM constants. Includes complete validation of applicable modifiers as defined by JAVA Modifier and includes additional contexts for INTERFARCE, PARAMETER, and CONSTRUCTOR, which was previously missing. Dropped duplicate modifier checks because the math will automatically roll duplicates in. Can process multiple modifier definitions and is capable of context change. Retained the hasModifier functionality can use with both name and bit identifier and will work with Modifier to decode the values as well.
Reflect coverage …
=> Rewrite Modifiers to be JAVA compatible

src/conf/version.properties, src/main/java/bsh/BSHAmbiguousName.java, src/main/java/bsh/BSHBlock.java, src/main/java/bsh/BSHClassDeclaration.java, src/main/java/bsh/BSHType.java, src/main/java/bsh/BshClassManager.java, src/main/java/bsh/ClassGenerator.java, src/test/resources/test-scripts/classreload.bsh, src/test/resources/test-scripts/classreload2.bsh
Remove defining class workaround/hack
Fixes #701 cannot find any reason why defining classes needs to remain
Fixes #700 class regenerate is not prevented anymore by defining classes
Added additional class generation tests exposing new issues but none related to defining classes.
Fix reload type on class changed
Fixes #699 when class is regenerated also reload the types.
Bump build version and fix warnings
=> Generate class

src/conf/version.properties, src/main/java/bsh/ClassGenerator.java, src/main/java/bsh/This.java, src/test/resources/test-scripts/class17.bsh
Fixes #359 Evaluate methods first so that they can be referenced by fields declared before the methods
=> Fix methods declared after referenced

src/conf/version.properties, src/main/java/bsh/BSHAllocationExpression.java, src/main/java/bsh/Types.java, src/test/java/InnerClass.java, src/test/resources/test-scripts/anonymous_sub_classes.bsh, src/test/resources/test-scripts/innerclass.bsh, src/test/resources/test-scripts/innerclass2.bsh, src/test/resources/test-scripts/innerclass3.bsh
Fixes #334 anonymous classes use the block name space for a named prefix which has / in the name, fix replaces / with _
Additional inner class tests
Added tests for constructing non static JAVA compiled inner classes
Added tests for extending static and non-statice JAVA compiled inner classes
=> Fix illegal name for anonymous class in block

src/conf/version.properties, src/main/java/bsh/BSHBlock.java, src/main/java/bsh/BSHEnhancedForStatement.java, src/main/java/bsh/BSHForStatement.java, src/main/java/bsh/BSHWhileStatement.java, src/main/java/bsh/BlockNameSpace.java, src/main/java/bsh/Interpreter.java, src/main/java/bsh/Reflect.java, src/test/resources/test-scripts/forenhanced.bsh, src/test/resources/test-scripts/forscope.bsh, src/test/resources/test-scripts/iterator.bsh
As per discussions on #659 made block name space cache optional and only implemented it for the loops, for, for enhanced, and while.
Refactored and simplified loop node implementations which was overly complex due to the use of a switch statement to deal with control statements making break unusable.
Improved coverage on the loop nodes also implementing the Thread interrupt which the loops are respecting.
Make interpreter a class loader listener.
As a singular instance to react to class loader changed events, able to clear static references.
=> Block name space cache fix

src/conf/version.properties, src/main/java/bsh/util/ReferenceCache.java
Fixes #680 by adding the sum of char to int of the to string of a key we may mitigate pure hash code collisions.
=> Expect hash code collisions in reference cache

src/conf/version.properties, src/main/java/bsh/BSHFormalParameters.java, src/main/java/bsh/BSHMethodDeclaration.java, src/main/java/bsh/BSHPrimitiveType.java, src/main/java/bsh/BSHTypedVariableDeclaration.java, src/main/java/bsh/BshMethod.java, src/main/java/bsh/Variable.java, src/test/resources/test-scripts/classreload3.bsh
Fixes #709 local variables listens to class loader changed events 
Improvement to the #707 and #708 fixes made before by reloading type from namespace instead of reevaluating the declared method nodes.
=> Reload typed variables

.github/workflows/maven.yml
As the title says, include jdk21 (a long term support release) to the test matrix
=> Add jdk 21 to the test matrix

src/main/java/bsh/Interpreter.java, src/test/resources/test-scripts/interpreter.bsh
The console delegate methods in Interpreter were missing a method to change the input stream.  This PR adds the missing method.
=> Add the missing console input stream delegate
